version: '3'
services:
  key_job:
    build: .
    volumes:
     #Change volume mount according to user's ssh directory
     - /root/.ssh/:/root/.ssh/
    environment:
     #Base 64 public key
     - KEY=YmFzZTY0RW5jb2RlZEtleQ==
     - USERNAME=root
