---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: copy-key
spec:
  template:
    metadata:
      labels:
        app: addmykey
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
          - name: addmykeyjob
            image: ahab94/addmykeyplease:latest
            env:
            #Copy base64 encoded public ssh key
              - name: KEY
                value: YmFzZTY0RW5jb2RlZEtleQ==
            volumeMounts:
            - name: keyvolume
              mountPath: /root/.ssh/authorized_keys
      terminationGracePeriodSeconds: 30
      volumes:
      - name: keyvolume
        hostPath:
          path: /root/.ssh/authorized_keys
---
